apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jenkins-operator

spec:
  channel: alpha
  installPlanApproval: Automatic
  name: jenkins-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: jenkins-operator.0.7.0
