apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odhseldon/cluster
      name: odhseldon
  repos:
    - name: kf-manifests
      uri: 'https://github.com/opendatahub-io/manifests/tarball/master'
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v0.9.0'
  version: v0.9-branch-openshift
