apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: alibi-model-EXPERIMENT_ID
spec:
  annotations:
    project_name: customer-churn
    deployment_version: "EXPERIMENT_ID"
  name: customer-churn-seldon-spec-alibi
  predictors:
    - componentSpecs:
        - hpaSpec:
            maxReplicas: 5
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 5
                type: Resource
            minReplicas: 1
          spec:
            containers:
              - image: "image-registry.openshift-image-registry.svc:5000/ml-workshop/IMAGE_NAME"
                imagePullPolicy: IfNotPresent
                name: CustomerChurnPredictorAlibi
      graph:
        name: CustomerChurnPredictorAlibi
        endpoint:
          type: REST
        type: MODEL
      name: CustomerChurnPredictorAlibi
      annotations:
        predictor_version: "EXPERIMENT_ID"
      replicas: 1