apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: alibi-model-EXPERIMENT_ID
spec:
  annotations:
    project_name: customer-churn
    deployment_version: "EXPERIMENT_ID"
  name: customer-churn-seldon-spec-alibi
  predictors:
    - componentSpecs:
        - hpaSpec:
            maxReplicas: 5
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 5
                type: Resource
            minReplicas: 1
          spec:
            containers:
              - image: "image-registry.openshift-image-registry.svc:5000/test/IMAGE_NAME"
                imagePullPolicy: Always
                name: customerchurnpredictoralibi
                env:
                  - name: MODEL_NAME
                    value: CustomerChurnTransformer
                  - name: SERVICE_TYPE
                    value: TRANSFORMER

              - image: "image-registry.openshift-image-registry.svc:5000/test/IMAGE_NAME"
                imagePullPolicy: Always
                name: customerchurnpredictoralibi
                env:
                  - name: MODEL_NAME
                    value: CustomerChurnPredictorAlibi
                  - name: SERVICE_TYPE
                    value: MODEL

      graph:
        children:
          - name: customerchurnpredictoralibi
            type: MODEL
            endpoint:
              type: REST
        name: customerchurntransformer
        endpoint:
          type: REST
        type: TRANSFORMER
      annotations:
        predictor_version: "EXPERIMENT_ID"
      replicas: 1